anguage: java
jdk:
- openjdk11
install: true
addons:
  sonarcloud:
    organization: xm-online
    token:
      secure: hVUf9fLK2qEhboQOmYmiYGoA8MgcPj463ohLHKxR9THDR7CRxPIDx36FABl98I5ORdwYT9GYxm+nqc2Vq5b8xuiPpGuWobmhhCDseVSfjlAYFWrOfbUIw/1TYxkUsgtWa1ZeR9AaNB3fBC5PhT+mgtUe0ojSYZAXEBv+fFXAvYmu4qPln4n1ZafONiqOEVJ/cXKybW2CX7P3QNYcdwKRx0zLg7pkudvNpbOaD0nw6zQIAXWPPcIqg4MHShvxWjC8JQgzr1pz+H/FPFA3K4P5bOIc6+nIdWXSsvK9XIXbxILhM3XsJ27RMH1418v+FH/ViQRWrSXDgc7fSNrYhFyIn277hKUhTuaC5/l6Oyv14/zzj2ZvAWDFA7sURJulWuB5jJpi9EI32ckCHkj/5sYbxvL4Ze0aFnYBNRexnLgOVuTemPJwk2nJx9WtsDlWG/9lZDiydcUGOwU48RAGc49lz5Oz0M5FpaRC1DNI2Nd52MNBA++AUv09mOYc8SCGBAoBeTpASwNO0yj8GK03mL7fgczcrMaAyZZ328Bo5ErfVqevFdG49hbJi3Uqyq2dk8nThCg97YOoRaMG9vwH8xZpM+z8EUUeUJD+Q4Cjd6zLlMskBFzL/KIMM1kbt6hqFwM3Jr57W0I6tujqBUYf5IllWBxZFjlrq7nBzC3uO6CNWW4=
    branches:
    - master

script:
  - set -e
  - "./gradlew --no-daemon --refresh-dependencies clean check test"
  - "./gradlew -x test -Pprod --no-daemon bootWar"
  - docker login -u $DOCKER_USER -p $DOCKER_PASS
  - export DOCKER_REPO=$(echo  -n $TRAVIS_REPO_SLUG | sed -e 's/^xm-online\//xmonline\//g')
  - export IMAGE_BRANCH=$(echo -n $TRAVIS_BRANCH | sed -e 's/\//-/g')
  - export PROJECT_VERSION="$IMAGE_BRANCH"
  - if [ "$IMAGE_BRANCH" == "master" ]; 
    then 
        PROJECT_VERSION=$(./gradlew -q  getProjectVersion);
        export SONAR_PK=$(echo  -n $TRAVIS_REPO_SLUG | sed -e 's/\//:/g');
        ./gradlew -x test --no-daemon sonarqube -Dsonar.projectKey="$SONAR_PK"
        -Dsonar.projectName="$SONAR_PK" -Dsonar.java.binaries="." -Dsonar.projectVersion="$IMAGE_BRANCH";
        TAGS="$PROJECT_VERSION $PROJECT_VERSION-$TRAVIS_BUILD_NUMBER $(echo $PROJECT_VERSION | awk -F '.' '{printf $1"."$2" "$1}') latest";
    else
        TAGS="$IMAGE_BRANCH $IMAGE_BRANCH-$TRAVIS_BUILD_NUMBER";
    fi
  - docker build -t app-docker-img --label commit_id="$TRAVIS_COMMIT" --label version="$PROJECT_VERSION" --label build_number="$TRAVIS_BUILD_NUMBER" --label build_url="$TRAVIS_BUILD_WEB_URL" --label git_url="$TRAVIS_REPO_SLUG" --label commit_message="$TRAVIS_COMMIT_MESSAGE" -f src/main/docker/Dockerfile .
  - for TAG in $TAGS;
    do
        docker tag app-docker-img $DOCKER_REPO:$TAG;
        docker push $DOCKER_REPO:$TAG;
    done

cache:
  directories:
  - "~/.gradle/"
env:
  global:
  - secure: G/mG3aBywVWtISl7nqAScFE4Wp8I//O4jMpt6xwiuWanfHMnbkljFGewFhdLohlTiOvAtuuAsNGtmZUV4MOFp1k8lAt/FfCC1EvRhXAndKgiDdRS+KVDXpwZv0skYflyl4iZ4sSNmrwQntOqjY+17cDAL0VzXzAKntfLXMLSSnbSrj9draHuf51Hv33HbC/v9lLJ5e156ySJlDf/JYQjgCr4+vceP8THVu4UXaHiGivC0uGQcDx/TDvQv+HuunEHg/8SIRa28iH58Jyc++ctUP4stwbyy6LkJQPxm6aZRJ1d2Fvo2vANQA+kHTj+zQdFaDSvevVQfwJgePD3+n+CdHsNMN0TweOMU4JLdya34HlKzlzY/C9kZ+i73FgRaAfiazIs3w8o2X/do29SpSREcjzx5tvt2QyvMtSmWHbQumKyBgIbCC/+JMUUNGnioO3c9NWO+k4hdgBzojsdKA8USl3TwDa6DuJN3lC6oNPx+J2ngYvNIuZkdpBj8YQKRDYnmFF4lkysHtxyn5/UzLcM02aNp19jqUasjdwEF3+VylWpCXatFj5+aCa9NgibV6iWnr3Xfc/kF1EMIJvzBuVX6UnIakH7V9Hb1QZPlhvPqclA7Rx8Wy8jgyiRCKXJVimVQlQzH+2181eY7hwt6bUUROkOya76H7Me65tnshvz0m8=
  - secure: PGH6JuJpL5VQoA/hQTl9zlP6XO4nw1lz5sXpHq61OXAFue9UkdgfSIhsxPawRSrEhu7I1+TEbNJJFwKC0gVfpH8czu6IHUC9NiNHGaXQG/k7/75ip+VoSqWQn4cDQLNGzedPqKE0Zcx03WimC9OwOuUFGo2sIxPHEzT8zv/wXOo81nsLQEgzRFOs+kS0DCCTqMUCNXER6cbn6F4OrYpoo+wY41pl+z/l5TAKyq0v/FTc70aS9KUnjXsBIo1vYsFfrixr5Iip2FiXksGVul1nEaRpE/x0Rs068KzOaAQUBh+fk37DRKC4lXn0H+KUIR/Slitu1IITgI3Fe58v4jKSwdAJGgg3168gSC+A2EMG6Omfc31NX/uqcCYKnnsk267e4CkhcQIeRqR/JNRUio0TiCsewKOL4fhimdz5mdWYSujPxgB7f1t16rOqSlxpsn5z2LxJEnUR3XCTA1hCgQRj3GshEY55fHzFrly826n/g1n5B1CoVvha2HqDH3/9Qj0cXFRizLmGwyGV55hA7g+KwlwP1616PmWac5edmM75P1UHD7V64sl9QRl7am42mrgYNsnZ57G6DhXS7cLHN4lNxWk+mRlRYOExGP3Xt3IOw7WiS+FMJM4OdUMw91fUOq6cDYoKX7eA4/avZcyuiYw/DewJ1uQXS2ugHWReZyO+we8=
notifications:
  slack:
    rooms:
      secure: rDBKbzw8IvA2sJPIBpSIQUfUi/hYVeMXF+Nx99+Exe58+L8eVqIVQEe8HvDOSVGUQjpb3Ycby7jEf011TxJlI8BdKuVeichXRog5wkbAd4Ii0LiuzWjsLK/4GqSHaQZUlea6AeSWW3/6TZezGkDS/CUp1VE2jccip7nbTDbn13VxU6OXp4eoCmi7ApcdCpiWW2j/CFGnXf6FXO1UujDz85Zeoz3OkErH0rmIeyykpxuahMJsD76QniCjMRwoItSlFWC4GAwH7zciD+Qz5kaJMLOQipBA0a1856/7GkDOchWJGfjqfe9VTvLxkKM5E0/VRBOjU4k1k+VC/wuBlfu5ikcVhsALynM3qVi1iTF+Z3+VQO0E7/7YT48tK6i+9vXtB3rMNKn+2gg6CvJW7PoVgo9bOTND7hgiLAUTMTFvSXQ5Yp7JiolSnnUKdxAtPXhMuwlvsg9jC01IYbGPj3DQ9gUDiB+FJRoWkVjnlNA1GoOVQwzKDiqr0z286VRDszhs4bu2UFh8SXH1IXiHoO49aPZ5/zKpd4U8icn1xaDx4Rv85vTmtkrsBcgZeasocRcpUZXabKZyyXvVPfDEErhZh1o0m6HwxN5PLXHsPD7qg3WKSXif8EMqaL2CR/dyu3TbitI75VXotCO3w43j8+vpYs8xO4/Oy3wO/xet/Rbaq+Y=
